# Generated by Django 5.2.8 on 2025-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
