# Generated by Django 5.2.8 on 2025-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_interviewtemplate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtranscript',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewtranscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
